The ui elements are modified and the user needs to press back button …
xwiki-contrib/android-authenticator pull request #11
Opened 2018-03-02 14:17 UTC by Koundinyalanka

…to go to previous screen. No need of previous button

2018-03-02 14:19 UTC, Koundinyalanka commented
@pa1pal please check this out

2018-03-02 14:26 UTC, pa1pal commented
@Koundinyalanka Please edit the description and give more details what you did to solve the issue, add some screenshots as well.

2018-03-02 15:19 UTC, Koundinyalanka commented
Done @pa1pal

2018-03-03 05:56 UTC, pa1pal requested changes
As I saw you updated gradle plugins versions, as it is outdated. 👍 
But also update the build tools version as it is ignored because minimum supported version for Gradle plugin 3.0.1 is 26.0.2.
Make it to the latest version.

2018-03-03 14:09 UTC, Koundinyalanka commented
ok @pa1pal

2018-03-03 14:35 UTC, Koundinyalanka commented
Dependencies are updated to latest stable version @pa1pal

2018-03-04 18:07 UTC, pa1pal reviewed
@Koundinyalanka why did you delete the `Button` code from `act_authenticator.xml`? The code there is much more generic rather adding that on every file. So revert back to there and change tint and other minor details for the issue there. 👍

2018-03-04 18:07 UTC, pa1pal commented on app/src/main/res/layout/viewflipper_setting_ip.xml
> +                android:text="Next"
Do add all the hardcoded values in their respective files. Strings, dimensions, colors etc. 
I know it wasn't managed from starting but adding new code should follow the guidelines.

2018-03-04 18:07 UTC, pa1pal commented on app/src/main/res/layout/viewflipper_setting_ip.xml
> +                android:layout_width="100dp"
Follow the android material design guidelines for sizes and styles, do not add any random values, refer to guidelines first: https://material.io/guidelines/components/buttons.html#buttons-style

2018-03-05 00:14 UTC, Koundinyalanka commented
@pa1pal I accept that the code in the act_authenticator.xml is more generic but according to new updates that I have added, There is no need for previous button(left button) as the user can go to previous screen by pressing back button. There will be only one next button and the position of the next button changes according to the screen for good look. I will find a more generic way to write this and I will add all hard coded values to respective files. Any other suggestions?

2018-03-19 23:46 UTC, Koundinyalanka commented
@pa1pal common colors,strings,dimensions are added to their respective value files.

2018-03-20 13:25 UTC, pa1pal approved these changes

2018-03-20 13:26 UTC, merged