ANDAUTH-57.
xwiki-contrib/android-authenticator pull request #34
Opened 2019-08-08 23:59 UTC by jaindiv26

Added support for OIDC (OpenId connect) into XWiki Authenticator.

Issue: - https://jira.xwiki.org/projects/ANDAUTH/issues/ANDAUTH-57?filter=allopenissues

2019-08-13 06:00 UTC, InsanusMokrassar requested changes
First changes for this PR

2019-08-13 06:00 UTC, InsanusMokrassar commented on app/src/main/java/org/xwiki/android/sync/AppContext.kt
> +var selectedAccount = ""
Again you are using global variables. Clear it, please.

2019-08-13 06:00 UTC, InsanusMokrassar commented on app/src/main/java/org/xwiki/android/sync/AppContext.kt
> +var selectedAccount = ""
You must replace it to another place and make it local

2019-08-13 06:00 UTC, InsanusMokrassar commented on app/src/main/java/org/xwiki/android/sync/activities/OIDC/OIDCActivity.kt
> +        if (requestCode == REQUEST_ACCESS_TOKEN) {
Replace with `when`:

```
when (requestCode) {
    REQUEST_ACCESS_TOKEN -> { ... }
    REQUEST_NEW_ACCOUNT -> { ... }
}
```

2019-08-13 06:00 UTC, InsanusMokrassar commented on app/src/main/java/org/xwiki/android/sync/activities/OIDC/OIDCAuthenticatorActivity.kt
> +            flow = AuthorizationCodeFlow.Builder(
Replace with:

```
AuthorizationCodeFlow.Builder(
    BearerToken.authorizationHeaderAccessMethod(),
    NetHttpTransport(),
    JacksonFactory(),
    GenericUrl(TOKEN_SERVER_URL),
    ClientParametersAuthentication(
        selectedAccount,
        ""
    ),
    selectedAccount,
    AUTHORIZATION_SERVER_URL
).run {
    setScopes(
        mutableListOf(
            "openid",
            "offline_access",
            "profile"
        )
    )
    build()
}
```

2019-08-13 06:34 UTC, jaindiv26 commented on app/src/main/java/org/xwiki/android/sync/activities/OIDC/OIDCAuthenticatorActivity.kt
> +            flow = AuthorizationCodeFlow.Builder(
Done.

2019-08-13 06:36 UTC, jaindiv26 commented on app/src/main/java/org/xwiki/android/sync/activities/OIDC/OIDCActivity.kt
> +        if (requestCode == REQUEST_ACCESS_TOKEN) {
Done.

2019-08-18 03:08 UTC, InsanusMokrassar approved these changes

2019-08-18 03:09 UTC, merged