ANDAUTH-67 Added Contributing.md file
xwiki-contrib/android-authenticator pull request #44
Opened 2020-03-03 17:24 UTC by somenath1435

Contributing.md contains all details necessary for a beginner level developer to be able to contribute to this project.

2020-03-03 19:05 UTC, InsanusMokrassar requested changes
The lists better to format as lists (for example, in the part where you write about forks). Besides, check that you are not using titles syntax (sharps) like lists

2020-03-03 19:05 UTC, InsanusMokrassar commented on CONTRIBUTING.md
> +## How to Contribute
Should start from #

2020-03-03 19:05 UTC, InsanusMokrassar commented on CONTRIBUTING.md
> +First please go through the [Community Contributions at Xwiki](https://dev.xwiki.org/xwiki/bin/view/Community/Contributing)
In markdown it is better to separate two paragraphs with two newlines

2020-03-03 19:05 UTC, InsanusMokrassar commented on CONTRIBUTING.md
> +Go to the repository on github at https://github.com/xwiki-contrib/android-authenticator.git.
Here must be used https://github.com/xwiki-contrib/android-authenticator

2020-03-04 10:11 UTC, somenath1435 commented
@InsanusMokrassar I've made changes

2020-03-04 11:10 UTC, InsanusMokrassar requested changes
As I said previously, for branch policy each subsection (which are not subsections currently) in most cases can be included in a list

2020-03-04 11:10 UTC, InsanusMokrassar commented on CONTRIBUTING.md
> +Type
It is must be a list

2020-03-04 11:10 UTC, InsanusMokrassar commented on CONTRIBUTING.md
> +Go to your version of the repository on github.
One more newline

2020-03-04 11:10 UTC, InsanusMokrassar commented on CONTRIBUTING.md
> +Click the green button “Create pull request”. Give a succinct and informative title, in the comment field give a short explanation of the changes and click the green button “Create pull request” agai
It is must be a list

2020-03-04 11:46 UTC, somenath1435 commented
@InsanusMokrassar please check now

2020-03-04 14:48 UTC, InsanusMokrassar requested changes

2020-03-04 14:48 UTC, InsanusMokrassar commented on CONTRIBUTING.md
> +# Sending pull requests:
Here must be ##

2020-03-04 14:48 UTC, InsanusMokrassar commented on CONTRIBUTING.md
> +# Change into that project directory (android-authenticator):
It is look like a part of previous subsection. I think, it would be better to replace it above

2020-03-04 14:48 UTC, InsanusMokrassar commented on CONTRIBUTING.md
> +* `$ git push origin master`
It is look like a hints. So, I think, it would be better to replace all of it in section `Hints` and fix their section level (I am about # number)

2020-03-04 18:57 UTC, somenath1435 commented
@InsanusMokrassar please take a look now

2020-03-04 19:35 UTC, InsanusMokrassar commented
> @InsanusMokrassar please take a look now

@somenath1435 I made a changes. Check them and if they are ok with the things you wished to include in this PR - I will merge it.

2020-03-04 19:51 UTC, somenath1435 commented
@InsanusMokrassar looks good to me

2020-03-06 11:05 UTC, InsanusMokrassar approved these changes

2020-03-06 11:11 UTC, tmortagne approved these changes

2020-03-06 11:11 UTC, merged