ANDAUTH-69 Remove Hardcoded Dimentions and Colors
xwiki-contrib/android-authenticator pull request #48
Opened 2020-03-04 11:34 UTC by somenath1435

Make use of colors.xml and dimens.xml

2020-03-04 16:10 UTC, InsanusMokrassar commented
please, update all pull requests according to updates in source repo

2020-03-04 19:10 UTC, somenath1435 commented
@InsanusMokrassar I've updated all of my PRs

2020-03-06 11:22 UTC, InsanusMokrassar requested changes
Please, check again all strings, there is some hardcoded, but I can't choose them during review. For example: https://github.com/xwiki-contrib/android-authenticator/pull/48/files#diff-e583f742aaca2eda54730c48f1fcc6f5R20

2020-03-06 11:22 UTC, InsanusMokrassar commented on app/src/main/res/layout/act_grant_permission.xml
>          android:minHeight="54dip"
You left this, please, fix it

2020-03-06 11:22 UTC, InsanusMokrassar commented on app/src/main/res/layout/activity_sync_settings.xml
>                                  android:textColor="#000000"
One more skipped

2020-03-06 11:22 UTC, InsanusMokrassar commented on app/src/main/res/layout/viewflipper_signin.xml
>                          android:layout_height="1dp"
One more hardcoded

2020-03-07 22:19 UTC, somenath1435 commented
@InsanusMokrassar I've made chamges

2020-03-08 21:10 UTC, InsanusMokrassar requested changes
https://github.com/xwiki-contrib/android-authenticator/pull/48/files#diff-e583f742aaca2eda54730c48f1fcc6f5R126
https://github.com/xwiki-contrib/android-authenticator/pull/48/files#diff-e583f742aaca2eda54730c48f1fcc6f5R22
https://github.com/xwiki-contrib/android-authenticator/pull/48/files#diff-cc2e231ce27ac95bc207fbbf102660bcR82
These lines are still hardcoded as and other in this review

2020-03-08 21:10 UTC, InsanusMokrassar commented on app/src/main/res/layout/viewflipper_signin.xml
>                          android:text="OpenID Connect"
Still hardcoded

2020-03-08 21:10 UTC, InsanusMokrassar commented on app/src/main/res/layout/activity_sync_settings.xml
>                                  android:text="Sync Account"
Still hardcoded

2020-03-08 21:10 UTC, InsanusMokrassar commented on app/src/main/res/layout/list_item_group.xml
>              android:text="Admin"
Still hardcoded

2020-03-08 21:10 UTC, InsanusMokrassar commented on app/src/main/res/layout/list_item_group.xml
>              android:text="creator:xwiki"
Still hardcoded

2020-03-09 12:18 UTC, somenath1435 commented
@InsanusMokrassar I've removed hardcoded strings as well

2020-03-10 07:45 UTC, InsanusMokrassar approved these changes

2020-03-10 07:46 UTC, InsanusMokrassar requested changes
Ok. Please recheck again all sources for absent of hardcoded strings/hints/dimens and I will merge it after check that everythin is look like ok

2020-03-10 07:46 UTC, InsanusMokrassar commented
@somenath1435 please, notify me, when you will recheck all again

2020-03-10 22:47 UTC, somenath1435 commented
@InsanusMokrassar I've checked , looks like this PR is ready

2020-03-11 06:12 UTC, InsanusMokrassar commented
> @InsanusMokrassar I've checked , looks like this PR is ready

Ok, let me check current state

2020-03-11 06:19 UTC, merged