ANDAUTH-72 created layout for landscape mode for signin viewflipper
xwiki-contrib/android-authenticator pull request #53
Opened 2020-03-09 15:33 UTC by somenath1435

Before:

![Screenshot_20200309-181238](https://user-images.githubusercontent.com/43093724/76230180-55cf3900-6249-11ea-8280-804cc0344684.png)

Now:

![Screenshot_20200309-190249](https://user-images.githubusercontent.com/43093724/76230197-5c5db080-6249-11ea-8c02-84801de3c3bd.png)

2020-03-09 16:09 UTC, tmortagne commented
The screenshot looks good indeed.

2020-03-13 02:53 UTC, InsanusMokrassar commented
Hello, @somenath1435 . I have seen the changes and wished to do a few by myself. I will try hard to do my best to complete these changes as soon as possible

2020-03-15 09:35 UTC, InsanusMokrassar commented
I have tried to refactor your improvement. It is almost the same (from a point of view of layouts), but it is having changed code related to oidc. First of all, I have changed the mechanism of showing OIDC button: now it is disabled in case of unavailability of OIDC auth
![Screenshot_20200315-152911_XWiki_Authenticator](https://user-images.githubusercontent.com/6850345/76698947-7fb5af00-66d2-11ea-9faa-4c83ffe4d46f.png)
![Screenshot_20200315-153050_XWiki_Authenticator](https://user-images.githubusercontent.com/6850345/76698950-85ab9000-66d2-11ea-8001-845bf3941f42.png)
![Screenshot_20200315-153011_XWiki_Authenticator](https://user-images.githubusercontent.com/6850345/76698952-88a68080-66d2-11ea-830f-5679e99a67f5.png)
![Screenshot_20200315-153015_XWiki_Authenticator](https://user-images.githubusercontent.com/6850345/76698953-8a704400-66d2-11ea-8165-5814f24f0db8.png)

2020-03-15 09:36 UTC, InsanusMokrassar commented
@somenath1435 are you agree to these changes?

2020-03-15 17:40 UTC, somenath1435 commented
@InsanusMokrassar looks great

2020-03-16 06:05 UTC, InsanusMokrassar commented
> @InsanusMokrassar looks great

Ok, waiting for @tmortagne review

2020-03-16 06:37 UTC, InsanusMokrassar requested changes
I found the problem that after rotating of screen we are coming back to the server setting up screen... If it will be possible, please, fix it

2020-03-16 09:21 UTC, tmortagne approved these changes

2020-03-16 21:52 UTC, somenath1435 commented
@InsanusMokrassar I'll create a new jira ticket for this

2020-03-17 23:24 UTC, somenath1435 commented
@InsanusMokrassar I've alread made one jira ticket for the issue you mentioned above, otherwise in my opinion this PR is ready

2020-03-18 02:54 UTC, InsanusMokrassar commented on app/src/main/res/values/strings.xml
> +    <string name="continueWithLandsacpe">---- Or continue with ----</string>
Redundant line, we should remove it

2020-03-18 02:54 UTC, InsanusMokrassar commented on app/src/main/java/org/xwiki/android/sync/utils/extensions/ViewGroup.kt
> +var ViewGroup.enabled: Boolean
Maybe, we should rewrite it with `View` receiver

2020-03-18 02:56 UTC, InsanusMokrassar commented
> @InsanusMokrassar I've alread made one jira ticket for the issue you mentioned above, otherwise in my opinion this PR is ready


You are right. I (or you) will made a small changes according to my last comments and merge it

2020-03-18 11:32 UTC, merged