ANDAUTH-73 check internet connection before sending request
xwiki-contrib/android-authenticator pull request #54
Opened 2020-03-09 15:55 UTC by somenath1435

Before sending request to server, we should check if internet connection is there or not. Otherwise, request should not be sent in first place and error message should be shown

2020-03-10 07:42 UTC, InsanusMokrassar requested changes

2020-03-10 07:42 UTC, InsanusMokrassar commented on app/src/main/java/org/xwiki/android/sync/activities/SignInViewFlipper.kt
> +                showErrorMessage("Check Internet Connection !!!")
At least, it must be extracted. It will be better to get string as usually

2020-03-10 07:42 UTC, InsanusMokrassar commented on app/src/main/java/org/xwiki/android/sync/utils/SystemTools.kt
> +fun checkNet(context: Context): Boolean {
I am not sure, but it is possible that will be better to use extension syntax like `fun Context.checkNet()`

2020-03-10 22:46 UTC, somenath1435 commented
@InsanusMokrassar PR is updated

2020-03-11 06:53 UTC, InsanusMokrassar requested changes

2020-03-11 06:53 UTC, InsanusMokrassar commented on app/src/main/res/values/strings.xml
> +    <string name="error_no_internet">Check Internet Connection !!!</string>
I think, here should be something like `Please, check the internet connection`

2020-03-11 18:07 UTC, somenath1435 commented
@InsanusMokrassar please check now

2020-03-13 20:42 UTC, somenath1435 commented
@InsanusMokrassar is this PR final or is there any other changes required??

2020-03-15 09:50 UTC, InsanusMokrassar requested changes

2020-03-15 09:50 UTC, InsanusMokrassar commented on app/src/main/res/values/strings.xml
> +    <string name="error_no_internet">Please Check Internet Connection</string>
Set here the value to "Please,  check the internet connection"

2020-03-15 17:39 UTC, somenath1435 commented
@InsanusMokrassar done

2020-03-16 06:20 UTC, InsanusMokrassar commented
@somenath1435 I have modified it a little bit, you can investigate it. Unfortunately, for now I am not sure that show message like we are doing this for now - is a better way. You can try to do it with some simple dialog with the same message and button like `ok` (there is a default buttons in android, I recommend you to read about this)

2020-03-16 06:21 UTC, InsanusMokrassar approved these changes

2020-03-16 20:12 UTC, somenath1435 commented
@InsanusMokrassar i've added alert dialog

![Screenshot_20200317-013053 1](https://user-images.githubusercontent.com/43093724/76795987-7c184a00-67f0-11ea-869c-fa636bd92675.png)

2020-03-17 07:02 UTC, InsanusMokrassar requested changes

2020-03-17 07:02 UTC, InsanusMokrassar commented on app/src/main/java/org/xwiki/android/sync/activities/SignInViewFlipper.kt
> +    fun showDialog(title: String, message:String){
I think, it would be better to replace it in some util file (for example, `Dialogs.kt`) with `Context` receiver like:

```kotlin
fun Context.showDialog(title: String?, message: String, onPositiveButton: (AlertDialog) -> Unit) { ... }
```

Besides, I  offer to make the title optional (`title: String?`) and set it up only when this value is not null

2020-03-17 07:02 UTC, InsanusMokrassar commented on app/src/main/res/values/colors.xml
> +    <color name="dialogButtonText">#e10a0a</color>
I think, it would be better to set here value to `@colors/error_color` (I mean set here value to the link to `error_color` value

2020-03-17 07:02 UTC, InsanusMokrassar commented on app/src/main/res/values/strings.xml
> +    <string name="ok">OK</string>
There is standard [ok](https://developer.android.com/reference/android/R.string#ok) string in Android

2020-03-17 23:19 UTC, somenath1435 commented
@InsanusMokrassar I've made the changes

2020-03-18 02:50 UTC, InsanusMokrassar requested changes

2020-03-18 02:50 UTC, InsanusMokrassar commented on app/src/main/java/org/xwiki/android/sync/utils/DialogUtils.kt
> +    if (!title.isNullOrEmpty()) builder.setTitle(title)
Will be better to replace with `title ?.also { builder.setTitle(it) }`

2020-03-18 02:50 UTC, InsanusMokrassar commented on app/src/main/java/org/xwiki/android/sync/activities/SignInViewFlipper.kt
> +
Redundant line

2020-03-18 02:50 UTC, InsanusMokrassar commented on app/src/main/java/org/xwiki/android/sync/activities/SignInViewFlipper.kt
> +                mContext.showDialog(mContext.getString(R.string.error),mContext.getString(R.string.error_no_internet))
In inline arguments should be used space after commas

2020-03-18 02:50 UTC, InsanusMokrassar commented on app/src/main/java/org/xwiki/android/sync/activities/SignInViewFlipper.kt
> +            else if (checkInput()) {
`else` must be in one line with closing bracket

2020-03-18 11:59 UTC, InsanusMokrassar approved these changes

2020-03-18 12:00 UTC, InsanusMokrassar commented
I made several changes and now alert dialog look like this:

![Screenshot_20200318-175822_XWiki_Authenticator](https://user-images.githubusercontent.com/6850345/76958656-5602bf00-6942-11ea-947b-75fe905f48b7.png)

@tmortagne please, review it and I will merge it if everything is ok

2020-03-18 13:03 UTC, tmortagne approved these changes

2020-03-18 13:06 UTC, merged